# Generated by Django 2.2.4 on 2019-09-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('hex', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ColorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colormatch.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('file', models.ImageField(max_length=120, upload_to='images/')),
                ('colors', models.ManyToManyField(blank=True, through='colormatch.ColorImage', to='colormatch.Color')),
            ],
        ),
        migrations.AddField(
            model_name='colorimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colormatch.Image'),
        ),
    ]
